# Form implementation generated from reading ui file './create.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewKeyPairDialog(object):
    def setupUi(self, NewKeyPairDialog):
        NewKeyPairDialog.setObjectName("NewKeyPairDialog")
        NewKeyPairDialog.resize(289, 258)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=NewKeyPairDialog)
        self.buttonBox.setGeometry(QtCore.QRect(40, 220, 231, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self._l1 = QtWidgets.QLabel(parent=NewKeyPairDialog)
        self._l1.setGeometry(QtCore.QRect(10, 20, 55, 17))
        self._l1.setObjectName("_l1")
        self._l2 = QtWidgets.QLabel(parent=NewKeyPairDialog)
        self._l2.setGeometry(QtCore.QRect(10, 60, 55, 17))
        self._l2.setObjectName("_l2")
        self.tbEmail = QtWidgets.QLineEdit(parent=NewKeyPairDialog)
        self.tbEmail.setGeometry(QtCore.QRect(120, 60, 151, 25))
        self.tbEmail.setObjectName("tbEmail")
        self.tbName = QtWidgets.QLineEdit(parent=NewKeyPairDialog)
        self.tbName.setGeometry(QtCore.QRect(120, 20, 151, 25))
        self.tbName.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.tbName.setObjectName("tbName")
        self._l3 = QtWidgets.QLabel(parent=NewKeyPairDialog)
        self._l3.setGeometry(QtCore.QRect(10, 100, 101, 17))
        self._l3.setObjectName("_l3")
        self.comboAlgorithm = QtWidgets.QComboBox(parent=NewKeyPairDialog)
        self.comboAlgorithm.setGeometry(QtCore.QRect(120, 100, 151, 25))
        self.comboAlgorithm.setObjectName("comboAlgorithm")
        self.comboAlgorithm.addItem("")
        self.comboAlgorithm.addItem("")
        self._l4 = QtWidgets.QLabel(parent=NewKeyPairDialog)
        self._l4.setGeometry(QtCore.QRect(10, 140, 101, 17))
        self._l4.setObjectName("_l4")
        self.comboSize = QtWidgets.QComboBox(parent=NewKeyPairDialog)
        self.comboSize.setGeometry(QtCore.QRect(120, 140, 151, 25))
        self.comboSize.setObjectName("comboSize")
        self.comboSize.addItem("")
        self.comboSize.addItem("")
        self.tbPassword = QtWidgets.QLineEdit(parent=NewKeyPairDialog)
        self.tbPassword.setGeometry(QtCore.QRect(120, 180, 151, 25))
        self.tbPassword.setInputMask("")
        self.tbPassword.setText("")
        self.tbPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.tbPassword.setObjectName("tbPassword")
        self._l5 = QtWidgets.QLabel(parent=NewKeyPairDialog)
        self._l5.setGeometry(QtCore.QRect(10, 180, 101, 17))
        self._l5.setObjectName("_l5")

        self.retranslateUi(NewKeyPairDialog)
        self.buttonBox.accepted.connect(NewKeyPairDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(NewKeyPairDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(NewKeyPairDialog)
        NewKeyPairDialog.setTabOrder(self.tbName, self.tbEmail)
        NewKeyPairDialog.setTabOrder(self.tbEmail, self.comboAlgorithm)
        NewKeyPairDialog.setTabOrder(self.comboAlgorithm, self.comboSize)
        NewKeyPairDialog.setTabOrder(self.comboSize, self.tbPassword)

    def retranslateUi(self, NewKeyPairDialog):
        _translate = QtCore.QCoreApplication.translate
        NewKeyPairDialog.setWindowTitle(_translate("NewKeyPairDialog", "New key pair"))
        self._l1.setText(_translate("NewKeyPairDialog", "Name:"))
        self._l2.setText(_translate("NewKeyPairDialog", "Email:"))
        self._l3.setText(_translate("NewKeyPairDialog", "Algorithm:"))
        self.comboAlgorithm.setItemText(0, _translate("NewKeyPairDialog", "RSA"))
        self.comboAlgorithm.setItemText(1, _translate("NewKeyPairDialog", "DSA+ElGamal"))
        self._l4.setText(_translate("NewKeyPairDialog", "Key size:"))
        self.comboSize.setItemText(0, _translate("NewKeyPairDialog", "1024 bits"))
        self.comboSize.setItemText(1, _translate("NewKeyPairDialog", "2048 bits"))
        self._l5.setText(_translate("NewKeyPairDialog", "Password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewKeyPairDialog = QtWidgets.QDialog()
    ui = Ui_NewKeyPairDialog()
    ui.setupUi(NewKeyPairDialog)
    NewKeyPairDialog.show()
    sys.exit(app.exec())
