# Form implementation generated from reading ui file './importkey.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImportDialog(object):
    def setupUi(self, ImportDialog):
        ImportDialog.setObjectName("ImportDialog")
        ImportDialog.resize(257, 173)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ImportDialog)
        self.buttonBox.setGeometry(QtCore.QRect(-90, 130, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tbPassphrase = QtWidgets.QLineEdit(parent=ImportDialog)
        self.tbPassphrase.setGeometry(QtCore.QRect(100, 90, 151, 25))
        self.tbPassphrase.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.tbPassphrase.setCursorPosition(0)
        self.tbPassphrase.setObjectName("tbPassphrase")
        self._l2 = QtWidgets.QLabel(parent=ImportDialog)
        self._l2.setGeometry(QtCore.QRect(10, 90, 101, 17))
        self._l2.setObjectName("_l2")
        self._l3 = QtWidgets.QLabel(parent=ImportDialog)
        self._l3.setGeometry(QtCore.QRect(10, 50, 55, 17))
        self._l3.setObjectName("_l3")
        self.tbKeyName = QtWidgets.QLineEdit(parent=ImportDialog)
        self.tbKeyName.setGeometry(QtCore.QRect(100, 10, 151, 25))
        self.tbKeyName.setObjectName("tbKeyName")
        self.tbKeyEmail = QtWidgets.QLineEdit(parent=ImportDialog)
        self.tbKeyEmail.setGeometry(QtCore.QRect(100, 50, 151, 25))
        self.tbKeyEmail.setObjectName("tbKeyEmail")
        self._l1 = QtWidgets.QLabel(parent=ImportDialog)
        self._l1.setGeometry(QtCore.QRect(10, 10, 55, 17))
        self._l1.setObjectName("_l1")

        self.retranslateUi(ImportDialog)
        self.buttonBox.accepted.connect(ImportDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ImportDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ImportDialog)
        ImportDialog.setTabOrder(self.tbKeyName, self.tbKeyEmail)
        ImportDialog.setTabOrder(self.tbKeyEmail, self.tbPassphrase)

    def retranslateUi(self, ImportDialog):
        _translate = QtCore.QCoreApplication.translate
        ImportDialog.setWindowTitle(_translate("ImportDialog", "Import key"))
        self.tbPassphrase.setPlaceholderText(_translate("ImportDialog", "(leave blank if public)"))
        self._l2.setText(_translate("ImportDialog", "Passphrase:"))
        self._l3.setText(_translate("ImportDialog", "Email:"))
        self._l1.setText(_translate("ImportDialog", "Name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ImportDialog = QtWidgets.QDialog()
    ui = Ui_ImportDialog()
    ui.setupUi(ImportDialog)
    ImportDialog.show()
    sys.exit(app.exec())
