# Form implementation generated from reading ui file './passphrase.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PassphraseDialog(object):
    def setupUi(self, PassphraseDialog):
        PassphraseDialog.setObjectName("PassphraseDialog")
        PassphraseDialog.resize(257, 98)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=PassphraseDialog)
        self.buttonBox.setGeometry(QtCore.QRect(-90, 60, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tbPassphrase = QtWidgets.QLineEdit(parent=PassphraseDialog)
        self.tbPassphrase.setGeometry(QtCore.QRect(100, 20, 151, 25))
        self.tbPassphrase.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.tbPassphrase.setCursorPosition(0)
        self.tbPassphrase.setObjectName("tbPassphrase")
        self._l2 = QtWidgets.QLabel(parent=PassphraseDialog)
        self._l2.setGeometry(QtCore.QRect(10, 20, 101, 17))
        self._l2.setObjectName("_l2")

        self.retranslateUi(PassphraseDialog)
        self.buttonBox.accepted.connect(PassphraseDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(PassphraseDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PassphraseDialog)

    def retranslateUi(self, PassphraseDialog):
        _translate = QtCore.QCoreApplication.translate
        PassphraseDialog.setWindowTitle(_translate("PassphraseDialog", "Enter key passphrase"))
        self.tbPassphrase.setPlaceholderText(_translate("PassphraseDialog", "(leave blank if public)"))
        self._l2.setText(_translate("PassphraseDialog", "Passphrase:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PassphraseDialog = QtWidgets.QDialog()
    ui = Ui_PassphraseDialog()
    ui.setupUi(PassphraseDialog)
    PassphraseDialog.show()
    sys.exit(app.exec())
