# Form implementation generated from reading ui file './receive.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ReceiveDialog(object):
    def setupUi(self, ReceiveDialog):
        ReceiveDialog.setObjectName("ReceiveDialog")
        ReceiveDialog.resize(474, 389)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ReceiveDialog)
        self.buttonBox.setGeometry(QtCore.QRect(120, 350, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self._l1 = QtWidgets.QLabel(parent=ReceiveDialog)
        self._l1.setGeometry(QtCore.QRect(10, 10, 55, 17))
        self._l1.setObjectName("_l1")
        self.tbMessage = QtWidgets.QTextEdit(parent=ReceiveDialog)
        self.tbMessage.setGeometry(QtCore.QRect(10, 30, 451, 151))
        self.tbMessage.setReadOnly(True)
        self.tbMessage.setObjectName("tbMessage")
        self.checkCompressed = QtWidgets.QCheckBox(parent=ReceiveDialog)
        self.checkCompressed.setGeometry(QtCore.QRect(10, 230, 91, 23))
        self.checkCompressed.setCheckable(True)
        self.checkCompressed.setObjectName("checkCompressed")
        self.checkSigned = QtWidgets.QCheckBox(parent=ReceiveDialog)
        self.checkSigned.setGeometry(QtCore.QRect(10, 210, 82, 23))
        self.checkSigned.setObjectName("checkSigned")
        self.checkEncrypted = QtWidgets.QCheckBox(parent=ReceiveDialog)
        self.checkEncrypted.setGeometry(QtCore.QRect(10, 190, 82, 23))
        self.checkEncrypted.setCheckable(True)
        self.checkEncrypted.setChecked(True)
        self.checkEncrypted.setObjectName("checkEncrypted")
        self.checkBase64ed = QtWidgets.QCheckBox(parent=ReceiveDialog)
        self.checkBase64ed.setGeometry(QtCore.QRect(10, 250, 121, 23))
        self.checkBase64ed.setCheckable(True)
        self.checkBase64ed.setObjectName("checkBase64ed")
        self._l2 = QtWidgets.QLabel(parent=ReceiveDialog)
        self._l2.setGeometry(QtCore.QRect(160, 250, 121, 20))
        self._l2.setObjectName("_l2")
        self._l3 = QtWidgets.QLabel(parent=ReceiveDialog)
        self._l3.setGeometry(QtCore.QRect(160, 190, 121, 20))
        self._l3.setObjectName("_l3")
        self._l4 = QtWidgets.QLabel(parent=ReceiveDialog)
        self._l4.setGeometry(QtCore.QRect(160, 220, 121, 20))
        self._l4.setObjectName("_l4")
        self._l5 = QtWidgets.QLabel(parent=ReceiveDialog)
        self._l5.setGeometry(QtCore.QRect(160, 280, 121, 20))
        self._l5.setObjectName("_l5")
        self.tbEncryptionKey = QtWidgets.QLineEdit(parent=ReceiveDialog)
        self.tbEncryptionKey.setGeometry(QtCore.QRect(290, 190, 171, 25))
        self.tbEncryptionKey.setReadOnly(True)
        self.tbEncryptionKey.setObjectName("tbEncryptionKey")
        self.tbEncryptionAlg = QtWidgets.QLineEdit(parent=ReceiveDialog)
        self.tbEncryptionAlg.setGeometry(QtCore.QRect(290, 220, 171, 25))
        self.tbEncryptionAlg.setReadOnly(True)
        self.tbEncryptionAlg.setObjectName("tbEncryptionAlg")
        self.tbSigningKey = QtWidgets.QLineEdit(parent=ReceiveDialog)
        self.tbSigningKey.setGeometry(QtCore.QRect(290, 250, 171, 25))
        self.tbSigningKey.setReadOnly(True)
        self.tbSigningKey.setObjectName("tbSigningKey")
        self.tbVerification = QtWidgets.QLineEdit(parent=ReceiveDialog)
        self.tbVerification.setGeometry(QtCore.QRect(290, 280, 171, 25))
        self.tbVerification.setReadOnly(True)
        self.tbVerification.setObjectName("tbVerification")

        self.retranslateUi(ReceiveDialog)
        self.buttonBox.accepted.connect(ReceiveDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(ReceiveDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ReceiveDialog)

    def retranslateUi(self, ReceiveDialog):
        _translate = QtCore.QCoreApplication.translate
        ReceiveDialog.setWindowTitle(_translate("ReceiveDialog", "Receive message"))
        self._l1.setText(_translate("ReceiveDialog", "Message:"))
        self.checkCompressed.setText(_translate("ReceiveDialog", "Compressed"))
        self.checkSigned.setText(_translate("ReceiveDialog", "Signed"))
        self.checkEncrypted.setText(_translate("ReceiveDialog", "Encrypted"))
        self.checkBase64ed.setText(_translate("ReceiveDialog", "Radix-64 encoded"))
        self._l2.setText(_translate("ReceiveDialog", "Signing key:"))
        self._l3.setText(_translate("ReceiveDialog", "Encryption key:"))
        self._l4.setText(_translate("ReceiveDialog", "Encryption algorithm:"))
        self._l5.setText(_translate("ReceiveDialog", "Verification status:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReceiveDialog = QtWidgets.QDialog()
    ui = Ui_ReceiveDialog()
    ui.setupUi(ReceiveDialog)
    ReceiveDialog.show()
    sys.exit(app.exec())
